version: 1.0
provider:
  name: openfaas
  gateway: 127.0.0.1:8080

functions:
  pyfunc:
    lang: python3
    handler: ./pyfunc
    image: alessionarder98/pyfunc:latest

  nodefunc:
    lang: node14
    handler: ./nodefunc
    image: alessionarder98/nodefunc:latest
    annotations:
      topic: cron-function
      schedule: "*/5 * * * *"


