name: build-and-deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::latest-dev
        
      - name: Get Repo Owner
        id: get_repo_owner
        run: >
          echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} |
          tr '[:upper:]' '[:lower:]')

      - name: Docker Login
        run: >
          docker login ghcr.io --username
          ${{ steps.get_repo_owner.outputs.repo_owner }}
          --password ${{secrets.DOCKER_PASSWORD}}

      - name: Publish functions
        run: >
          OWNER="${{ steps.get_repo_owner.outputs.repo_owner }}"
          TAG="latest"
          faas-cli publish
          --extra-tag ${{ github.sha }}
          --platforms linux/amd64

      - name: Login
        run: >
          faas-cli login --gateway ${{secrets.OPENFAAS_URL}} --password ${{secrets.OPENFAAS_PASSWORD}}

      - name: Deploy
        run: >
          OWNER="${{ steps.get_repo_owner.outputs.repo_owner }}"
          TAG="${{ github.sha }}"
          faas-cli deploy --gateway ${{secrets.OPENFAAS_URL}}
